### ISSUE TITLE
Using streamlit: version of urllib3 is incompatible with ssl

### ISSUE THREAD

**Issue by voynow** [zeit/now#10409]
09:00:49.305 | Running "vercel build"
09:00:49.813 | Vercel CLI 32.1.0
09:00:50.363 | Installing dependencies...
09:00:50.801 | Collecting datasets (from -r /vercel/path0/requirements.txt (line 1))
09:00:50.801 | Obtaining dependency information for datasets from https://files.pythonhosted.org/packages/66/f8/38298237d18d4b6a8ee5dfe390e97bed5adb8e01ec6f9680c0ddf3066728/datasets-2.14.4-py3-none-any.whl.metadata

...

09:01:23.230 |  
09:01:23.376 | Traceback (most recent call last):
09:01:23.376 | File "/usr/local/bin/streamlit", line 8, in <module>
09:01:23.376 | sys.exit(main())
09:01:23.376 | File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
09:01:23.377 | return self.main(*args, **kwargs)
09:01:23.377 | File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
09:01:23.377 | rv = self.invoke(ctx)
09:01:23.377 | File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
09:01:23.377 | return _process_result(sub_ctx.command.invoke(sub_ctx))
09:01:23.377 | File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
09:01:23.378 | return ctx.invoke(self.callback, **ctx.params)
09:01:23.378 | File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
09:01:23.378 | return __callback(*args, **kwargs)
09:01:23.378 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/cli.py", line 233, in main_run
09:01:23.378 | _main_run(target, args, flag_options=kwargs)
09:01:23.378 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/cli.py", line 269, in _main_run
09:01:23.378 | bootstrap.run(file, command_line, args, flag_options)
09:01:23.378 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 430, in run
09:01:23.378 | asyncio.run(run_server())
09:01:23.378 | File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
09:01:23.378 | return loop.run_until_complete(main)
09:01:23.378 | File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
09:01:23.379 | return future.result()
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 419, in run_server
09:01:23.379 | _on_server_start(server)
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 161, in _on_server_start
09:01:23.379 | _print_url(server.is_running_hello)
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/streamlit/web/bootstrap.py", line 285, in _print_url
09:01:23.379 | external_ip = net_util.get_external_ip()
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/streamlit/net_util.py", line 46, in get_external_ip
09:01:23.379 | response = _make_blocking_http_get(_AWS_CHECK_IP, timeout=5)
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/streamlit/net_util.py", line 91, in _make_blocking_http_get
09:01:23.379 | import requests
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
09:01:23.379 | import urllib3
09:01:23.379 | File "/usr/local/lib/python3.9/site-packages/urllib3/__init__.py", line 41, in <module>
09:01:23.379 | raise ImportError(
09:01:23.379 | ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
09:01:23.549 | Error: Command "streamlit run app.py" exited with 1

**Comment by viceice** [comment]
I've now created a custom python build (v3.12.1) with openssl 1.1 support which works fine 💪 

- https://github.com/renovatebot/renovatebot.github.io/pull/387
- https://github.com/containerbase/python-prebuild/tree/main/amzn-2
