### ISSUE TITLE
severless function giving  Error: ENOENT: no such file or directory, 

### ISSUE THREAD

**Issue by shadab97** [zeit/now#10787]
### Discussed in https://github.com/vercel/vercel/discussions/10786

<div type='discussions-op-text'>

<sup>Originally posted by **shadab97** October 31, 2023</sup>
### Question

I am accessing a  file  from the server page in app directory
file path
components/navbar/navbar_01/index.tsx

from some page in app dir I am using my  server function
path app/component/abc/index.tsx

my server function

```
import fs from "fs"
import path from "path"

export async function getComponentFileText(componentFilePath: string) {
  const codeFile = await fs.readFileSync(
    path.resolve(process.cwd(), "components", componentFilePath),
    "utf-8"
  )
  return codeFile
}
```

on local it is a working file but on vecel it gives an error

```
Error: ENOENT: no such file or directory, open '/var/task/components/showcase/navbars/nav_02/index.tsx'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at getComponentFileText (/var/task/.next/server/app/(MainLayout)/components/[componentName]/page.js:1:5382)
    at Iframe (/var/task/.next/server/app/(MainLayout)/components/[componentName]/page.js:1:5664)
    at ev (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:75:11059)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:75:21868
    at Array.toJSON (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:75:25185)
    at stringify (<anonymous>)
    at eT (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:75:13688)
    at eP (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:75:14214) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/task/components/showcase/navbars/nav_02/index.tsx'
}
```
also don't why vercel appending "/var/task/" in file ulr
</div>

**Comment by trek** [comment]
Hi @shadab97,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
