### ISSUE TITLE
vercel dev never uses config file when --local-config option is specified in monorepos

### ISSUE THREAD

**Issue by izhan** [zeit/now#10862]
## Repro
1. Have a monorepo (we use turborepo, where our main app is in `apps/web`)
2. Add a config file to `apps/web/vercel-dev.json`
3. Run the command `vercel dev --local-config ./apps/web/vercel-dev.json` from the root
4. Observe that your config is never applied

## Root cause:
The offending line is https://github.com/vercel/vercel/blob/main/packages/cli/src/util/dev/server.ts#L551. The config path will always be relative to the web app (`apps/web`) and not the monorepo root. Thus in the above example, it'll return `apps/web/apps/web/vercel-dev.json` and fail silently

This is a very similar root cause to a Remix config bug earlier this year: https://github.com/vercel/vercel/pull/9518

**Comment by lassiter** [comment]
I am also experiencing this issue.

for reference here is a debug output:

```shell
➜  heimdall git:(chore/webhooks) ✗ pnpm exec vercel dev -A vercel.json --debug
> [debug] [2025-07-18T06:01:44.623Z] Found config in provided --local-config path /Users/lassiter/code/mindpalace/apps/heimdall/vercel.json
(node:10226) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:10226) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
Vercel CLI 32.7.2
> [debug] [2025-07-18T06:01:44.634Z] user supplied known subcommand: "dev"
> [debug] [2025-07-18T06:01:44.853Z] Found ".git/config" - detected "/Users/lassiter/code/mindpalace" as repo root
> [debug] [2025-07-18T06:01:44.862Z] Spinner invoked (Retrieving project…) with a 1000ms delay
> [debug] [2025-07-18T06:01:44.871Z] #1 → GET https://api.vercel.com/teams/team_E...3
> [debug] [2025-07-18T06:01:44.873Z] #2 → GET https://api.vercel.com/v9/projects/prj_xo...cl?teamId=team_E...3
> [debug] [2025-07-18T06:01:45.189Z] #1 ← 200 OK: sfo1::ssjll-1752818505192-c702656ebe63 [318ms]
> [debug] [2025-07-18T06:01:45.195Z] #2 ← 200 OK: sfo1::hbczb-1752818505189-a5ef75543e05 [322ms]
> [debug] [2025-07-18T06:01:45.199Z] Fetching Environment Variables of project prj_xos...cl and target undefined
> [debug] [2025-07-18T06:01:45.200Z] #3 → GET https://api.vercel.com/v1/env/pull/prj_xos...cl?source=vercel-cli%3Adev&teamId=team_E...3
> [debug] [2025-07-18T06:01:45.307Z] #3 ← 200 OK: sfo1::hbczb-1752818505317-0d5d781a1cd7 [107ms]
Error: /Users/lassiter/code/mindpalace/apps/heimdall/apps/heimdall doesn't exist
> [debug] [2025-07-18T06:01:45.314Z] Error: /Users/lassiter/code/mindpalace/apps/heimdall/apps/heimdall doesn't exist
    at DevServer._start (/Users/lassiter/code/mindpalace/node_modules/.pnpm/vercel@32.7.2/node_modules/vercel/dist/index.js:187630:17)
    at DevServer.start (/Users/lassiter/code/mindpalace/node_modules/.pnpm/vercel@32.7.2/node_modules/vercel/dist/index.js:187618:36)
    at dev (/Users/lassiter/code/mindpalace/node_modules/.pnpm/vercel@32.7.2/node_modules/vercel/dist/index.js:188158:19)
    at async main4 (/Users/lassiter/code/mindpalace/node_modules/.pnpm/vercel@32.7.2/node_modules/vercel/dist/index.js:188321:12)
    at async main13 (/Users/lassiter/code/mindpalace/node_modules/.pnpm/vercel@32.7.2/node_modules/vercel/dist/index.js:199084:18)
```
