### ISSUE TITLE
`Error [ERR_REQUIRE_ESM]: require() of ES Module` from vercel dependency

### ISSUE THREAD

**Issue by kevinreber** [zeit/now#11102]
## Summary
Integrated Sentry into my Remix app that is deployed via Vercel and getting this error message during build [(see PR)](https://github.com/kevinreber/ai-icon-generator/pull/95)
```
Running "yarn run build"
--
17:57:28.365 | yarn run v1.22.17
17:57:28.398 | $ remix build --sourcemap && sentry-upload-sourcemaps --org kevin-reber --project javascript-remix
17:57:29.165 | info  building... (NODE_ENV=production)
17:57:29.165 | warn  🚨  source maps enabled in production
17:57:29.165 | ┃ You are using `--sourcemap` to enable source maps in production,
17:57:29.165 | ┃ making your server-side code publicly visible in the browser.
17:57:29.165 | ┃ This is highly discouraged!
17:57:29.165 | ┃ If you insist, ensure that you are using environment variables for secrets
17:57:29.166 | ┃ and are not hard-coding them in your source.
17:57:29.166 | ┗
17:57:36.365 | info  built (7.1s)
17:57:36.456 | /vercel/path0/node_modules/cliui/build/index.cjs:291
17:57:36.456 | const stringWidth = require('string-width');
17:57:36.456 | ^
17:57:36.456 |  
17:57:36.456 | Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/string-width/index.js from /vercel/path0/node_modules/cliui/build/index.cjs not supported.
17:57:36.456 | Instead change the require of index.js in /vercel/path0/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
17:57:36.456 | at Object.<anonymous> (/vercel/path0/node_modules/cliui/build/index.cjs:291:21)
17:57:36.457 | at Object.<anonymous> (/vercel/path0/node_modules/yargs/build/index.cjs:1:60678)
17:57:36.457 | at Object.<anonymous> (/vercel/path0/node_modules/yargs/index.cjs:5:30)
17:57:36.457 | at Object.<anonymous> (/vercel/path0/node_modules/@sentry/remix/scripts/sentry-upload-sourcemaps.js:2:15) {
17:57:36.457 | code: 'ERR_REQUIRE_ESM'
17:57:36.457 | }
17:57:36.457 |  
17:57:36.457 | Node.js v20.9.0
17:57:36.470 | error Command failed with exit code 1.
17:57:36.471 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:57:36.493 | Error: Command "yarn run build" exited with 1
```
Screenshots below
![CleanShot 2024-01-28 at 18 10 33@2x](https://github.com/vercel/community/assets/42260999/485fdcd1-3cdf-4296-969b-47076c1b6baf)
![CleanShot 2024-01-28 at 18 19 06@2x](https://github.com/vercel/community/assets/42260999/85584d57-f200-46ff-998a-48100fb48e93)

Seems strange that this issue is coming from `/vercel/path0/node_modules/cliui/build/index.cjs`, but did not run into this before attempting to integrate Sentry.

Also confirming my `package.json` is set to `"type": "module"`

## Steps to Reproduce
Issue with occurs during build (`yarn run build`) but did not run into this issue before attempting to integrate Sentry

## References
- Sentry Remix Integration: https://docs.sentry.io/platforms/javascript/guides/remix/
- PR with failed build: https://github.com/kevinreber/ai-icon-generator/pull/95 
- Deployed app: https://www.pixelstudioai.com/

**Comment by kevin-dev71** [comment]
i have the same error but when i try to run 'yarn test' with jest

**Comment by yuzushioh** [comment]
I have the same error

**Comment by justyn-clark** [comment]
<img width="1389" alt="Screenshot 2024-03-21 at 11 50 34 AM" src="https://github.com/vercel/vercel/assets/11221796/df35d1f9-3b88-48cd-a262-1fe1884ee683">

<img width="1313" alt="Screenshot 2024-03-21 at 11 55 22 AM" src="https://github.com/vercel/vercel/assets/11221796/9e31ed44-107e-4956-a5c2-dd60b89d17ce">

______

I was happy about finally getting to deploy Remix with Vite on Vercel and was doing so rapidly for the past 2 weeks and all of a sudden in the past 2 days, without me touching anything I'm getting the same. 

Literally did nothing and now I can't deploy and my production app is down. This is not cool.

**Comment by juliomuhlbauer** [comment]
same error

![image](https://github.com/vercel/vercel/assets/53458125/dc28403f-f2c2-45ef-8cda-0ed546fedc52)

**Comment by TooTallNate** [comment]
@kevinreber I checked out your repo + sentry branch, and I see the same failure locally, so I don't think this is specific to Vercel. The error happens within the `sentry-upload-sourcemaps` command, when cliui attempts to `require('string-width')` which is seemingly an ESM module.

I found this related issue (https://github.com/yargs/cliui/issues/138). Looks like this was a `yarn` bug. It works correctly when I install the deps with `npm` instead of `yarn`. I suggest you do the same.

For anyone else in this thread, if switching off of `yarn` doesn't help, please share a reproduction if you would like me to take a closer look.

**Comment by mheob** [comment]
I currently have the same problem. I use `bun`. Locally, all is fine.

![image](https://github.com/user-attachments/assets/a6310eb1-17bf-4a1f-912d-55d461ec52b3)

**Comment by Morbden** [comment]
Same error here

![image](https://github.com/user-attachments/assets/91eb926c-cc0c-4d32-9b46-e8d44db71f98)

When I try redeploy action, works, but normal deploy not works. Why?...

![image](https://github.com/user-attachments/assets/62a14133-6851-4c40-8ae2-5315c963d76b)

**Comment by CentillionJinx** [comment]
![image](https://github.com/user-attachments/assets/324ccefe-f62f-45ce-a5d7-f157d0d682bd)

Same here

**Comment by davidlhw** [comment]
stil facing the same issue with `bun` on `"next": "14.2.13"`
project - https://github.com/AfterClass-io/afterclass.io-v2/tree/0f382fd827df2ad056f1815e848a1df5b121accc

![image](https://github.com/user-attachments/assets/8c7f37da-f3e7-4e90-88d3-b51863569265)

works well locally.

```bash
~$ bun -v
1.1.29

~$ bun run build
$ next build
  ▲ Next.js 14.2.12
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data    
 ✓ Generating static pages (15/15)
 ✓ Collecting build traces
 ✓ Finalizing page optimization
# ...snipped
```

not sure if it makes a difference but vercel seems to be using an older version of bun

![image](https://github.com/user-attachments/assets/80bbd525-7cbd-4c00-9496-b1814a974766)


## Workaround

manually overriding build config on vercel to use this setup works as a workaround for me:

`Settings > General > Build & Development Settings > Project Settings`

![image](https://github.com/user-attachments/assets/eb0c6871-85a4-44e3-b61d-b5cf3d7b7829)

**Comment by mkpoli** [comment]
For now, if you are using `bun` and `SvelteKit`, replace `@sveltekit/adapter-auto` with `@sveltekit/adapter-vercel` can temporarily fix the problem.

**Comment by gabrielmaldi** [comment]
> When I try redeploy action, works, but normal deploy not works. Why?...

Redeploy works if you uncheck the `Use existing Build Cache` option.

**Comment by davidlhw** [comment]
issue seems to be fixed for me, nothing was done on my end

```
Vercel CLI 37.12.0
bun install v1.1.30 (7996d06b)
```

![image](https://github.com/user-attachments/assets/69d789f7-d212-4f55-b608-c8e2d1d7251e)
![image](https://github.com/user-attachments/assets/8ff34317-d5cf-4884-824f-209c743d7e5b)

**Comment by proevilz** [comment]
I've suddenly started getting this error, seemingly out of no where. No idea what to do... it builds locally just fine.
```
> Build error occurred
Error: require() of ES Module /vercel/path0/node_modules/nanoid/non-secure/index.js from /vercel/path0/node_modules/postcss/lib/input.js not supported.
Instead change the require of index.js in /vercel/path0/node_modules/postcss/lib/input.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (node_modules/postcss/lib/input.js:3:18) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by nxtvoid** [comment]
I had the same error with vercel (`nextjs 14.2.7`) and `bun v1.1.38`.

What I did was drowngrade my local bun (to `v1.1.34`), delete the bun.lockb and redo a `bun i` and upload this file to the repo so vercel can detect this new file, this is the only way it worked for me :(

One thing I noticed is that vercel uses `bun install v1.1.36 (ededc168)`, when this version doesn't exist (on the bun website) > https://bun.sh/blog

**Comment by MattIPv4** [comment]
👀 A few folks, including myself, have run into this in relation to https://github.com/jsdom/jsdom/issues/3959.

Everything I can see (including logging `process.version`) in Vercel would indicate that 22.18.0 is running when you select 22.x, which _should_ allow for requiring of ES Modules (this was [added in 22.12.0](https://nodejs.org/en/blog/release/v22.12.0)). However, as I'm sure folks are aware, you still hit this error. I've opened a high-priority support ticket with Vercel regarding this, as we ran into this JSDom issue unexpectedly in production, and have included a minimal reproduction, which they've acknowledged.

I'll try to remember to keep this thread updated as we hear more from support on this.

**Comment by distor-sil3nt** [comment]
Any updates on this, @MattIPv4? We use `jsdom` as a direct dependency and get the same error when bundling the app. Would be great if this gets resolved.

**Comment by MattIPv4** [comment]
They closed my ticket a week ago with no fix, just the workarounds folks already are aware of, and a vague promise that they'll fix it soon:

> Thank you for your patience while our team investigated this issue. We sincerely apologize for the delay in receiving an update from our internal team.
> 
> As confirmed, this appears to be a current limitation that was recently discovered as part of an ongoing issue with React Router and JSdom. The team has identified it as a bug, and it’s being addressed in the latest versions.
> 
> In the meantime, you can use one of the following workarounds to mitigate the issue:
> 
> • Use overrides to apply a temporary fix, or
> • Downgrade to an earlier version of JSdom until the patched release becomes available.
> 
> Please keep an eye on the changelog and upcoming releases for the fixed version once it’s published.
> 
> This support ticket will now be closed. Should you have any further questions or need additional assistance, please don’t hesitate to reach out.

**Comment by MattIPv4** [comment]
As a little further update, this is also an issue in Vercel's new Node.js 24.x runtime support 🙃 I've opened a follow-up support ticket...

**Comment by MattIPv4** [comment]
Okay, we have good news and context! I ended up pinging some engineers on Twitter (X), and [got a reply](https://x.com/tomlienard/status/1996502284591890899) that explained why this behavior is how it is:

> Lambda disables this flag by default because it's still in experimental status (stage 1.2) and not stable, which we follow to prevent sudden breaking changes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html

The engineer also recommended the workaround that Lambda itself recommends, setting `NODE_OPTIONS=--experimental-require-module`. *However*, after testing this myself, that doesn't currently work. I've flagged this to them, and have been [assured that a fix should be going out next week](https://x.com/tomlienard/status/1996932396629844247), so that folks will finally be able to get past this error: 

> Quick update, I have a fix for this that will be rolled out over the next few business days
>
> This was a regression for those two specific options (--experimental-require-module, --experimental-detect-module) when used within NODE_OPTIONS

They also escalated the fact that this deviation from default Node.js behavior (and the workaround) is not currently documented anywhere on Vercel's side.

**Comment by MattIPv4** [comment]
🎉 Vercel has fixed this, you can now set `NODE_OPTIONS=--experimental-require-module` to get past this error and opt back into the default Node.js behaviour. We also needed to set `VERCEL_USE_BYTECODE_CACHING=0`, as instructed by support, to force Vercel to regenerate the runtime bytecode for our project (as we were then hitting `SyntaxError: Cannot use import statement outside a module` with just the flag set).

Will follow up with them about getting this added to their docs properly.

**Comment by swarnava** [comment]
Thanks @MattIPv4 for reporting this! 🫡

**Comment by swarnava** [comment]
We have added documentation for this here: https://vercel.com/docs/functions/runtimes/node-js/advanced-node-configuration#experimental-node.js-require-of-es-module

**Comment by ChALkeR** [comment]
This still causes a lot of confusion in the ecosystem, with bugreports over ERR_REQUIRE_ESM spawning across multiple repos, while it's actually AWS Lambda which is at fault

The decision to disable require(ESM) makes no sense.

Also, it's underdocumented on AWS (docs only mention 22, not 24) and wrong / FUD: require(ESM) is stable and not going away from Node.js. It was in "not going away" mode once it was is enabled by default in Node.js
