### ISSUE TITLE
ERROR: @rollup/rollup-linux-x64-gnu not found for serverless function running on Vercel

### ISSUE THREAD

**Issue by mhbtz1** [zeit/now#11665]
I have created a web application using Express.js and deployed it as a serverless function to Vercel. The web application uses React with Typescript and Vite for module bundling / server side rendering. However, when querying one of the endpoints via user interaction, I get the following error:

```
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
at requireWithFriendlyError (/var/task/node_modules/rollup/dist/native.js:59:9)
at Object.<anonymous> (/var/task/node_modules/rollup/dist/native.js:68:76)
at Module._compile (node:internal/modules/cjs/loader:1358:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
at Module.load (node:internal/modules/cjs/loader:1208:32)
at Module._load (node:internal/modules/cjs/loader:1024:12)
at /opt/rust/nodejs.js:1:11508
at Function.Qt (/opt/rust/nodejs.js:1:11878)
at Q.e.<computed>.K._load (/opt/rust/nodejs.js:1:11478)
at cjsLoader (node:internal/modules/esm/translators:348:17) {
[cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
Require stack:
- /var/task/node_modules/rollup/dist/native.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
at Module._load (node:internal/modules/cjs/loader:986:27)
at /opt/rust/nodejs.js:1:11508
at Function.Qt (/opt/rust/nodejs.js:1:11878)
at Q.e.<computed>.K._load (/opt/rust/nodejs.js:1:11478)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at requireWithFriendlyError (/var/task/node_modules/rollup/dist/native.js:41:10)
at Object.<anonymous> (/var/task/node_modules/rollup/dist/native.js:68:76)
at Module._compile (node:internal/modules/cjs/loader:1358:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/var/task/node_modules/rollup/dist/native.js' ]
}
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 581.13 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```

Here is my vercel.json folder (I have written an Express server in api/server.js and have exposed it to the web application). Very simple, I am currently only using one function:

```
{ 
    "version": 2, 
    "rewrites": [{ "source": "/(.*)", "destination": "/api/server.js" }]

}
```

The actual function seems to be getting queried, but terminates with an error with code "FUNCTION_INVOCATION_FAILED".

Any thoughts about why this may be happening? I have not seen an issue for something like this in Vercel, and I tried:

1. Explicitly adding @rollup/rollup-linux-x64-gnu as a production dependency in package.json(), but this did not work
2.  Explicitly importing '@rollup/rollup-linux-x64-gnu' in api/server.js, since I had read that the way that serverless functions are compiled for Vercel doesn't use package.json, but uses the main dependencies for the given function.

But none of these approaches worked.

**Comment by islamzaoui** [comment]
same issue here for my sveltekit project with static adapter and bun

```bash
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
--
02:29:29.626 | at requireWithFriendlyError (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:59:9)
02:29:29.626 | at Object.<anonymous> (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:68:76)
02:29:29.626 | ... 3 lines matching cause stack trace ...
02:29:29.626 | at Module._load (node:internal/modules/cjs/loader:1022:12)
02:29:29.626 | at cjsLoader (node:internal/modules/esm/translators:366:17)
02:29:29.626 | at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
02:29:29.626 | at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
02:29:29.626 | at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
02:29:29.626 | [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
02:29:29.626 | Require stack:
02:29:29.627 | - /vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js
02:29:29.627 | at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
02:29:29.627 | at Module._load (node:internal/modules/cjs/loader:984:27)
02:29:29.627 | at Module.require (node:internal/modules/cjs/loader:1231:19)
02:29:29.627 | at require (node:internal/modules/helpers:179:18)
02:29:29.627 | at requireWithFriendlyError (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:41:10)
02:29:29.627 | at Object.<anonymous> (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:68:76)
02:29:29.627 | at Module._compile (node:internal/modules/cjs/loader:1369:14)
02:29:29.627 | at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
02:29:29.627 | at Module.load (node:internal/modules/cjs/loader:1206:32)
02:29:29.627 | at Module._load (node:internal/modules/cjs/loader:1022:12) {
02:29:29.627 | code: 'MODULE_NOT_FOUND',
02:29:29.627 | requireStack: [
02:29:29.627 | '/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js'
02:29:29.627 | ]
02:29:29.627 | }
02:29:29.627 | }
02:29:29.627 |  
02:29:29.627 | Node.js v20.12.2
02:29:29.632 | error: script "build" exited with code 1
02:29:29.636 | Error: Command "bun run build" exited with 1
```

**Comment by islamzaoui** [comment]
> same issue here for my sveltekit project with static adapter and bun
> 
> ```shell
> Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
> --
> 02:29:29.626 | at requireWithFriendlyError (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:59:9)
> 02:29:29.626 | at Object.<anonymous> (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:68:76)
> 02:29:29.626 | ... 3 lines matching cause stack trace ...
> 02:29:29.626 | at Module._load (node:internal/modules/cjs/loader:1022:12)
> 02:29:29.626 | at cjsLoader (node:internal/modules/esm/translators:366:17)
> 02:29:29.626 | at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
> 02:29:29.626 | at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
> 02:29:29.626 | at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
> 02:29:29.626 | [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
> 02:29:29.626 | Require stack:
> 02:29:29.627 | - /vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js
> 02:29:29.627 | at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
> 02:29:29.627 | at Module._load (node:internal/modules/cjs/loader:984:27)
> 02:29:29.627 | at Module.require (node:internal/modules/cjs/loader:1231:19)
> 02:29:29.627 | at require (node:internal/modules/helpers:179:18)
> 02:29:29.627 | at requireWithFriendlyError (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:41:10)
> 02:29:29.627 | at Object.<anonymous> (/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js:68:76)
> 02:29:29.627 | at Module._compile (node:internal/modules/cjs/loader:1369:14)
> 02:29:29.627 | at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
> 02:29:29.627 | at Module.load (node:internal/modules/cjs/loader:1206:32)
> 02:29:29.627 | at Module._load (node:internal/modules/cjs/loader:1022:12) {
> 02:29:29.627 | code: 'MODULE_NOT_FOUND',
> 02:29:29.627 | requireStack: [
> 02:29:29.627 | '/vercel/path0/node_modules/vite/node_modules/rollup/dist/native.js'
> 02:29:29.627 | ]
> 02:29:29.627 | }
> 02:29:29.627 | }
> 02:29:29.627 |  
> 02:29:29.627 | Node.js v20.12.2
> 02:29:29.632 | error: script "build" exited with code 1
> 02:29:29.636 | Error: Command "bun run build" exited with 1
> ```

I fixed this issue by changing sveltekit adapter from static to vercel

**Comment by fregante** [comment]
Not a Vercel bug, it's https://github.com/npm/cli/issues/4828, as the error suggests.

There are a few solutions in that thread but they might not work

**Comment by Ritikchhipa5** [comment]
Add the code as below to package.json and try npm install again.
Now you may successfully build your project on Linux and Windows.

```
`  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  },
  "optionalDependencies": {
    "@rollup/rollup-linux-x64-gnu": "4.9.5"
  }`
```

**Comment by thanhhoang0794** [comment]
anything news ? still error

**Comment by ShubhamOulkar** [comment]
override @rollup works, I faced this problem on Vercel deployment with vite bundler and pnpm package manager. 
`"pnpm": {
    "overrides": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }`

**Comment by nellysbr** [comment]
I was experiencing this same issue in a project built with **Astro** using the **Vercel adapter**. Here's how I managed to work around it:

### ✅ Steps to fix the issue (at least for the majority of my projects):

1. Check the version of `@rollup/rollup-linux-x64-gnu` in your `package-lock.json`.
2. Delete both the `node_modules` folder and the `package-lock.json` file and do `npm install` (or pnpm).
3. After that, the version of `@rollup/rollup-linux-x64-gnu` will likely be updated to the latest one.
4. In your `package.json`, add the following:

```json
   "dependencies": {},
   "devDependencies": {},
   "optionalDependencies": {
     "@rollup/rollup-linux-x64-gnu": "<YOUR_VERSION>"
   },
   "overrides": {
     "vite": {
       "rollup": "npm:@rollup/wasm-node"
     }
   }
```

5. Again, delete node_modules and package-lock.json, then run npm install.

6. Try deploying your project again and check if the issue is resolved.

> ⚠️ **Note**: As of today, the latest version of `@rollup/rollup-linux-x64-gnu` for me is `4.40.1`. You can replace `<YOUR_VERSION>` with whatever version works best in your environment (you can probably just add `optionalDependencies` and `overrides` in you package.json).


Until a definitive fix is released, this seems to be a reliable workaround — especially by setting the `optionalDependencies` and overriding Rollup with `npm:@rollup/wasm-node`, depending on your package manager or build tool.

Hope this helps!

**Comment by AntonioCoppe** [comment]
I'm experiencing the exact same issue as described in the original post, with a similar setup: an Express.js backend bundled with esbuild, frontend using React/TypeScript/Vite, deployed as a serverless function on Vercel. The error occurs at runtime when hitting API endpoints, causing 500 responses and process exits.

Error details (from Vercel logs, as of July 17, 2025):

```text
Error: Cannot find module @rollup
/rollup-linux-x64-gnu. npm has a bug related to optional dependencies [(https://github.com/npm/cli/issues/4828)](https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/var/task/node_modules/rollup/dist/native.js:64:9)
    at Object.<anonymous> (/var/task/node_modules/rollup/dist/native.js:73:76)
    at Module.<anonymous> (/opt/rust/bytecode.js:2:1435)
    at A.l._compile (/opt/rust/bytecode.js:2:3160)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1282:12)
    at /opt/rust/nodejs.js:2:12456
    at Function.Ar (/opt/rust/nodejs.js:2:12834)
    at De.e.<computed>._e._load (/opt/rust/nodejs.js:2:12426) {
  [cause]: Error: Cannot find module '@rollup
/rollup-linux-x64-gnu'
  Require stack:/var/task/node_modules/rollup/dist/native.js
  at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
  at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
  at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
  at Function.<anonymous> (node:internal/modules/cjs/loader:1211:37)
  at /opt/rust/nodejs.js:2:12456
  at Function.Ar (/opt/rust/nodejs.js:2:12834)
  at De.e.<computed>._e._load (/opt/rust/nodejs.js:2:12426)
  at TracingChannel.traceSync (node:diagnostics_channel:322:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
  at Module.require (node:internal/modules/cjs/loader:1487:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/var/task/node_modules/rollup/dist/native.js' ]
  }
}

Node.js process exited with exit status: 1.
```
The logs above can help with debugging the issue.

My setup:
- Node.js: v20.x (Vercel's default)
- Package manager: Yarn (v1.22.22)
- Build command: `vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outfile=api/index.js`
- vercel.json: Simple rewrites to route everything to `/api/index.js`
- Rollup is pulled in indirectly via Vite (v5.4.19)

What I've tried (without success):
- Adding `"@rollup/rollup-linux-x64-gnu": "4.21.3"` to `dependencies` or `optionalDependencies`.
- Using Yarn resolutions: `"resolutions": { "rollup": "npm:@rollup/wasm-node@4.21.3", "vite/rollup": "npm:@rollup/wasm-node@4.21.3" }` (with `@rollup/wasm-node` in dependencies).
- Cleaning node_modules and yarn.lock, reinstalling.
- Forcing include in vercel.json: `"functions": { "api/index.js": { "includeFiles": "node_modules/@rollup/rollup-linux-x64-gnu/**" } }`.
- Switching to npm with equivalent overrides—same error.

The app works perfectly locally (macOS arm64), but fails on Vercel (Linux x64). Builds succeed, but runtime crashes on any endpoint invocation. No Rollup warnings in build logs.

Has anyone found a reliable fix for Yarn/Vite setups in 2025? Or is switching adapters/bundlers the only way? Thanks!

**Comment by adamatronix** [comment]
> I was experiencing this same issue in a project built with **Astro** using the **Vercel adapter**. Here's how I managed to work around it:
> 
> ### ✅ Steps to fix the issue (at least for the majority of my projects):
> 1. Check the version of `@rollup/rollup-linux-x64-gnu` in your `package-lock.json`.
> 2. Delete both the `node_modules` folder and the `package-lock.json` file and do `npm install` (or pnpm).
> 3. After that, the version of `@rollup/rollup-linux-x64-gnu` will likely be updated to the latest one.
> 4. In your `package.json`, add the following:
> 
>    "dependencies": {},
>    "devDependencies": {},
>    "optionalDependencies": {
>      "@rollup/rollup-linux-x64-gnu": "<YOUR_VERSION>"
>    },
>    "overrides": {
>      "vite": {
>        "rollup": "npm:@rollup/wasm-node"
>      }
>    }
> 5. Again, delete node_modules and package-lock.json, then run npm install.
> 6. Try deploying your project again and check if the issue is resolved.
> 
> > ⚠️ **Note**: As of today, the latest version of `@rollup/rollup-linux-x64-gnu` for me is `4.40.1`. You can replace `<YOUR_VERSION>` with whatever version works best in your environment (you can probably just add `optionalDependencies` and `overrides` in you package.json).
> 
> Until a definitive fix is released, this seems to be a reliable workaround — especially by setting the `optionalDependencies` and overriding Rollup with `npm:@rollup/wasm-node`, depending on your package manager or build tool.
> 
> Hope this helps!

Doesn't seem to work for me. Switched to pnpm, but still no.

**Comment by fregante** [comment]
So this no longer appears to be a npm issue. They reportedly fixed it in v11. `rollup-linux-x64-gnu` appears in my lockfile but Vercel is not installing it.

Is this because the build environment does not match the deployment environment?

Anyway, this fixed it for me (after deleting `node_modules` and the lockfile). I use rollup directly, not via Vite

```js
	"dependencies": {
		"rollup": "npm:@rollup/wasm-node",
	},
	"overrides": {
		"rollup": "npm:@rollup/wasm-node"
	},
```
