### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by tarex** [zeit/now#18]
Having syntax error while using `now@beta` , version is `now@8.0.0-beta.1`
node version `7.3.0` , npm `5.2.0`
```
/usr/local/lib/node_modules/now/out/now.js:36
const main = async argv_ => {
                   ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Am I missing something ?

**Comment by rauchg** [comment]
Can you try with Node 8 in the mean time? The eventual release with be rolled out with [`pkg`](https://github.com/zeit/pkg)

**Comment by tarex** [comment]
Thanks for the quick response, its working now 👍

**Comment by gianpaj** [comment]
What's the min required version of Node and npm?

I'm getting the same issue with:
```
$ node --version
v6.10.2
$ npm --version
4.6.1
```
