### ISSUE TITLE
Uncaught ReferenceError on `now aws login`

### ISSUE THREAD

**Issue by e-beach** [zeit/now#25]
Trying out this library on Windows (Git-Bash), I got an exception immediately:
```
$ now aws login
> We'll need your AWS credentials in order to comunicate with their API.
  To provision a dedicated set of tokens for `now`, do the following:

  1. Go to https://console.aws.amazon.com/iam
  2. Click on "Users" in the left menubar
  3. Click on "Add user"
  4. Give your user a name and select "Programmatic access"
  5. In the "Permissions" step, select
     "Attach existing policies directly"
     and then
     "AdministratorAccess" (or pick your own)
  6. After the "Review" step, grab your keys and paste them below:

> Error! An unexpected error occurred!
  ReferenceError: restore is not defined
    at Promise (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\util\input\text.js:32:7)
    at Promise (<anonymous>)
    at textInput (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\util\input\text.js:27:10)
    at Object.login (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\providers\aws\login.js:104:31)
    at <anonymous> ReferenceError: restore is not defined
    at Promise (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\util\input\text.js:32:7)
    at Promise (<anonymous>)
    at textInput (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\util\input\text.js:27:10)
    at Object.login (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\out\providers\aws\login.js:104:31)
    at <anonymous>
```

OS: `Windows 10 x64`
node version: `v8.1.4`
npm version: `5.0.3`

**Comment by e-beach** [comment]
I would also argue that a tool that aspires to be a universal deploy engine ought to work on Git-Bash (I had to use cmd.exe).

**Comment by nkzawa** [comment]
@e-beach yeah, makes sense. Created issue about Git Bash https://github.com/zeit/now/issues/25 .
