### ISSUE TITLE
Creating AWS API Resources: InvalidParameterException

### ISSUE THREAD

**Issue by e-beach** [zeit/now#27]
The my-project directory contains the sample node server from the README. I'm using Windows 10, node v8.1.4, now 8.0.0-beta.1

```
C:\Users\Elliott\me\projects\my-project>now
> Deploying "~\me\projects\my-project" (aws) (us-west-1)
√ Build generated a 1.67kB zip [276ms]
√ Initialized IAM role "now-default-role" [-250ms]
/ Creating API resources> Error! An unexpected error occurred!
  InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
    at Object.extractError (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\protocol\rest_json.js:37:8)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at callNextListener (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at IncomingMessage.onEnd (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\event_listeners.js:269:13)
    at emitNone (events.js:110:20) InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
    at Object.extractError (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\protocol\rest_json.js:37:8)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at callNextListener (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at IncomingMessage.onEnd (C:\Users\Elliott\AppData\Roaming\npm\node_modules\now\node_modules\aws-sdk\lib\event_listeners.js:269:13)
    at emitNone (events.js:110:20)
- Creating API resources
```

**Comment by e-beach** [comment]
I ran the command again and it worked, but that doesn't mean problem is solved. This problem must occur with timing of editing Amazon Trust Relationships  as discussed in https://stackoverflow.com/questions/36419442/the-role-defined-for-the-function-cannot-be-assumed-by-lambda.

**Comment by nkzawa** [comment]
Thanks for the report 👍 
I can reproduce the issue by removing the `now-default-role` role and run `now aws deploy`.
