### ISSUE TITLE
Node version updates breaking native deps

### ISSUE THREAD

**Issue by JChanceHud** [zeit/now#3633]
I began encountering the following error at about 21:00 UTC on January 20:

```
2020-01-21T19:22:08.670Z	undefined	ERROR	Error: The module '/var/task/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/routes/users.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Duration: 454.54 ms  Billed Duration: 500 ms  Memory Size: 3008 MB  Max Memory Used: 52 MB	
```

A simple redeployment of the repository solved the problem, but in the time between each request was throwing errors. I don't know if this is the right repo for this but changes to the serverless execution environment should trigger an auto-rebuild instead of silently failing (like above).

Thanks

**Comment by styfle** [comment]
Hi @JChanceHud  

You can try pinning to a specific version of Node like `10.x` or `12.x` if your dependencies require a specific version of Node.

See the following documentation: https://zeit.co/docs/runtimes#official-runtimes/node-js/node-js-version

Since `node_modules` is cached, its possible the auto-upgrade to Node 12 caused the natives deps built with Node 10 to try to run with Node 12. I'll take a look to see how we can improve caching in this case, thanks!

**Comment by JChanceHud** [comment]
Pinning seems like an orthogonal feature to this issue.

If you publish a repo with the intent of running it on the latest available env the expectation is that changes will trigger a rebuild of necessary dependencies. Otherwise the project is a timebomb.

I don't know what your internal architecture looks like but it seems like busting the dependency cache on Node version upgrades for any repos set to use the latest version would solve the problem.

**Comment by styfle** [comment]
Indeed, we'll make sure too invalidate the cache on the next Node.js version bump, thanks!
