### ISSUE TITLE
Potentially missing information in documentation with regards to deploying a Django application.

### ISSUE THREAD

**Issue by dnk8n** [zeit/now#3644]
I am trying to get a simple Django application deployed to zeit / now.

What I read in documentation leads me to believe that all I need is a python file within an api directory in the root, which defines an app variable. 

Please see https://gitlab.com/dnk8n/dnk8n_api/. There you will see an api directory [with index.py inside](https://gitlab.com/dnk8n/dnk8n_api/blob/master/api/index.py).

The `from src.api.asgi import application as app` import works successfully which indicates src/api is available. I don't understand why module api.settings cannot be found though (see below for error generated upon executing `now dev` (and then navigating to http://localhost:3000/api/).

```
> Now CLI 16.7.3 dev (beta) — https://zeit.co/feedback
> Ready! Available at http://localhost:3000
> Building @now/python@latest:api/index.py
Installing required dependencies...
> Built @now/python@latest:api/index.py [13s]
Traceback (most recent call last):
  File "/home/dean/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 147, in <module>
    lambda_runtime_main()
  File "/home/dean/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 127, in lambda_runtime_main
    fn = lambda_runtime_get_handler()
  File "/home/dean/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 113, in lambda_runtime_get_handler
    mod = importlib.import_module(module_name)
  File "/home/dean/miniconda3/envs/django-now/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/zeit-fun-429011b173777/now__handler__python.py", line 7, in <module>
    import api.index
  File "/tmp/zeit-fun-429011b173777/api/index.py", line 1, in <module>
    from src.api.asgi import application as app
  File "/tmp/zeit-fun-429011b173777/src/api/asgi.py", line 16, in <module>
    application = get_asgi_application()
  File "/tmp/zeit-fun-429011b173777/django/core/asgi.py", line 12, in get_asgi_application
    django.setup(set_prefix=False)
  File "/tmp/zeit-fun-429011b173777/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/tmp/zeit-fun-429011b173777/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/tmp/zeit-fun-429011b173777/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/tmp/zeit-fun-429011b173777/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/dean/miniconda3/envs/django-now/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'api.settings'
LambdaError: RequestId: 34f8aa13-beb8-475b-8c29-dc79c39c7982 Process exited before completing request
    at Lambda.<anonymous> (/home/dean/node/lib/node_modules/now/dist/index.js:2:3505604)
    at Generator.next (<anonymous>)
    at fulfilled (/home/dean/node/lib/node_modules/now/dist/index.js:2:3503491)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by dnk8n** [comment]
I refactored and now `now dev` works

Would be interested if there was a solution that required less control over how I structure my project though.

https://gitlab.com/dnk8n/dnk8n_api/commit/7231ecac1e3e0dc06bc6f3db0afe81bd814a5d95

What I did, is move the index.py and requirements.txt into the src directory. It was happier. Was unable to have /graphql as route, so matched it with /api.
