### ISSUE TITLE
GCP deploy on next@beta throws TypeError

### ISSUE THREAD

**Issue by danoc** [zeit/now#64]
Hello! When running `now` for a GCP deployment I'm running into:

```
⠋ Building and bundling your app…> Error! An unexpected error occurred!
  TypeError: builders[desc.type] is not a function
    at build (/snapshot/now/dist/now.js:1590:29)
    at deploy (/snapshot/now/dist/now.js:5960:25) TypeError: builders[desc.type] is not a function
    at build (/snapshot/now/dist/now.js:1590:29)
    at deploy (/snapshot/now/dist/now.js:5960:25)
```

Has anyone else seen this issue? I'm using `8.0.0-beta.8`.

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#757
