### ISSUE TITLE
The server is rewriting the URLs of my backend API requests

### ISSUE THREAD

**Issue by kristjanmar** [zeit/now#7329]
It looks like NextJS or the Vercel server is rewriting the URLs for some of my backend API requests.

Sometimes it removes the = symbols, or replaces some symbols with weird characters.

This is showing up in my error logs as 500 errors from the backend server because it doesn't know how to interpret these requests.

I'm using getServersideProps, fetch and the URL string is made with JS template literals.

let url = `select?type=${type}&main=${main}&count=${count}&sort=${sort}&columns=${cols}&filters=${filters}`

Here's an example:

```
500 /_next/data/_9cBFu6gG_-Pa4FWIOxG3/markets/premarket.json
2022-01-20T09:04:13.479Z		ERROR	FetchError: invalid json response body at https://api.stockanalysis.com/wp-json/sa/select**?typestocks&mainpremarketChangePercent&count &sortÞsc&columnss,n,premarketChange,premarketPrice,marketCap,premarketChangePercent&filtersprice-over-1,close-over-**1,volume-over-1000 reason: Unexpected end of JSON input
    at /var/task/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getData (/var/task/.next/server/chunks/9111.js:1298:16)
    at async getSelect (/var/task/.next/server/chunks/6768.js:2260:20)
    at async getServerSideProps (/var/task/.next/server/pages/markets/premarket.js:108:18)
    at async Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:555:20)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:1406:38)
    at async /var/task/node_modules/next/dist/server/base-server.js:1501:28
    at async /var/task/node_modules/next/dist/server/response-cache.js:63:36 {
  type: 'invalid-json',
  page: '/markets/premarket'
}
RequestId:  Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Vercel is rewriting this:
select?type=stocks&main=premarketChangePercent&count=20&sort=desc&columns=s,n,premarketChange,premarketPrice,marketCap,premarketChangePercent&filters=price-over-1,close-over-1,volume-over-1000

To this:

/select?typestocks&mainpremarketChangePercent&count &sortÞsc&columnss,n,premarketChange,premarketPrice,marketCap,premarketChangePercent&filtersprice-over-1,close-over-1,volume-over-1000

The request being sent to my backend removes a bunch of "=" symbols, removes "=20" and replaces "=desc" with "Þsc".

**Comment by trek** [comment]
Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
