### ISSUE TITLE
`node-fetch` not working with Node.js Function

### ISSUE THREAD

**Issue by leerob** [zeit/now#7540]
## Steps To Reproduce

**api/test.js**

```js
import fetch from 'node-fetch';

export default async function handler() {
  const res = await fetch('https://api.github.com/repos/vercel/vercel', {});

  const data = await res.json();
  return response.status(200).json({ data });
}
```

**package.json**

```json
{
  "name": "funtion-esm-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-fetch": "^3.2.2"
  }
}
```

Run `vercel dev` from the root of the project.

```
▲  funtion-esm-test/ vercel dev
Vercel CLI 24.0.0
> Ready! Available at http://localhost:3000
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/leerob/Developer/scratch/funtion-esm-test/node_modules/node-fetch/src/index.js from /Users/leerob/Developer/scratch/funtion-esm-test/api/test.js not supported.
Instead change the require of index.js in /Users/leerob/Developer/scratch/funtion-esm-test/api/test.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/ts-node/dist/index.js:534:20)
    at Object.<anonymous> (/Users/leerob/Developer/scratch/funtion-esm-test/api/test.js:6:38)
    at Module.m._compile (/Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/ts-node/dist/index.js:538:29)
    at Object.require.extensions.<computed> [as .js] (/Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/ts-node/dist/index.js:540:16)
    at getListener (/Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/@vercel/node/dist/launcher.js:70:11)
    at /Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/@vercel/node/dist/launcher.js:81:5
    at main (/Users/leerob/.nvm/versions/node/v16.13.1/lib/node_modules/vercel/node_modules/@vercel/node/dist/dev-server.js:103:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

I am able to work around this by downgrading to `node-fetch@2` and using a CJS import `const fetch = require('node-fetch')`.

**Comment by verbose117** [comment]
You should set `type` to `module` in package.json.

**Comment by styfle** [comment]
I confirmed this works when `package.json` has `type: module` which is necessary for node-fetch > 3

(*Note: there is a typo in the original code because `response` is undefined*)

Some other alternatives to use `node-fetch@3`:

- Use `.mjs` extension
- Use dynamic import `await import('node-fetch')` which works with CJS

Learn more: https://nodejs.org/api/packages.html

**Comment by user72356** [comment]
`"type": "module"` does not work for me, I still get the error message.
