### ISSUE TITLE
Error: listen EADDRINUSE: while deploying ExpressJS API.

### ISSUE THREAD

**Issue by jaikarans** [zeit/now#7664]
### Discussed in https://github.com/vercel/vercel/discussions/7663

<div type='discussions-op-text'>

<sup>Originally posted by **jaikarans** April  9, 2022</sup>
[https://github.com/jaikarans/ecommerce/tree/master/server](https://github.com/jaikarans/ecommerce/tree/master/server)
i am trying to deploy above expressJS api on vercel it is giving this error

EDIT: i am using linux.

[18:41:20.394] $ node server.js
[18:41:21.147] success Already up-to-date.
[18:41:21.151] Done in 1.37s.
[18:41:21.227] events.js:377
[18:41:21.228]       throw er; // Unhandled 'error' event
[18:41:21.228]       ^
[18:41:21.228] 
[18:41:21.228] Error: listen EADDRINUSE: address already in use :::5000
[18:41:21.229]     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[18:41:21.229]     at listenInCluster (net.js:1379:12)
[18:41:21.229]     at Server.listen (net.js:1465:7)
[18:41:21.229]     at Object.<anonymous> (/vercel/path2/server/server.js:11:8)
[18:41:21.229]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[18:41:21.230]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[18:41:21.230]     at Module.load (internal/modules/cjs/loader.js:950:32)
[18:41:21.230]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[18:41:21.230]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
[18:41:21.230]     at internal/main/run_main_module.js:17:47
[18:41:21.230] Emitted 'error' event on Server instance at:
[18:41:21.230]     at emitErrorNT (net.js:1358:8)
[18:41:21.230]     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
[18:41:21.231]   code: 'EADDRINUSE',
[18:41:21.231]   errno: -98,
[18:41:21.231]   syscall: 'listen',
[18:41:21.231]   address: '::',
[18:41:21.231]   port: 5000
[18:41:21.231] }
[18:41:21.264] error Command failed with exit code 1.
[18:41:21.265] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[18:41:21.281] Error: Command "yarn run build" exited with 1
</div>

**Comment by Abhiram716** [comment]
Hi @jaikarans did you find any solutions for this?

**Comment by jaikarans** [comment]
> Hi @jaikarans did you find any solutions for this?

I got busy with something else and moved on, so I really don't have any solution.

**Comment by trek** [comment]
Hi @jaikarans,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
