### ISSUE TITLE
vercel dev hangs on macOS m1 w/ sveltekit

### ISSUE THREAD

**Issue by sjsadowski** [zeit/now#7744]
## Versions
CLI Version: 24.2.0
OS: macOS monterrey 12.3.1
kernel: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
node: 18.0.0
sveltekit: next-324

## Relevant info
On macOS 12.3.1 (M1) vercel dev hangs when attempting to proxy requests, eventually times out and crashes. This is not reproduceable on Linux (Fedora 35/kernel 5.16.20)

Debug output:
```sh
$ vercel dev --debug
Vercel CLI 24.2.0
> [debug] [2022-05-01T15:00:24.010Z] user supplied known subcommand: "dev"
> [debug] [2022-05-01T15:00:24.086Z] #1 → GET https://api.vercel.com/v1/frameworks
> [debug] [2022-05-01T15:00:24.090Z] Spinner stopped (Retrieving project…)
> [debug] [2022-05-01T15:00:24.090Z] Spinner invoked (Retrieving project…) with a 1000ms delay
> [debug] [2022-05-01T15:00:24.092Z] #2 → GET https://api.vercel.com/teams/team_vbsX6T2sFs0Zfpt8rPDAyGow?
> [debug] [2022-05-01T15:00:24.092Z] #3 → GET https://api.vercel.com/v8/projects/prj_sW12FKf4gzSRRQMFookL14aZSDrK?teamId=team_vbsX6T2sFs0Zfpt8rPDAyGow
> [debug] [2022-05-01T15:00:24.376Z] #1 ← 200 OK: sfo1:sfo1:sfo1::sfo1::85h9l-1651417224304-969ee5cb025d [290ms]
> [debug] [2022-05-01T15:00:24.395Z] #2 ← 200 OK: sfo1::b8mjl-1651417224318-96399c7538c3 [303ms]
> [debug] [2022-05-01T15:00:24.397Z] #3 ← 200 OK: sfo1::qk5nn-1651417224322-6498ff4eaa93 [305ms]
> [debug] [2022-05-01T15:00:24.400Z] Fetching Environment Variables of project prj_sW12FKf4gzSRRQMFookL14aZSDrK and target development
> [debug] [2022-05-01T15:00:24.402Z] #4 → GET https://api.vercel.com/v8/projects/prj_sW12FKf4gzSRRQMFookL14aZSDrK/env?target=development&decrypt=true&teamId=team_vbsX6T2sFs0Zfpt8rPDAyGow
> [debug] [2022-05-01T15:00:24.402Z] Fetching System Environment Values of project prj_sW12FKf4gzSRRQMFookL14aZSDrK
> [debug] [2022-05-01T15:00:24.403Z] #5 → GET https://api.vercel.com/v6/projects/prj_sW12FKf4gzSRRQMFookL14aZSDrK/system-env-values?teamId=team_vbsX6T2sFs0Zfpt8rPDAyGow
> [debug] [2022-05-01T15:00:24.651Z] #5 ← 200 OK: sfo1::m49pw-1651417224589-510fd3d7e58d [248ms]
> [debug] [2022-05-01T15:00:24.652Z] #4 ← 200 OK: sfo1::28tdm-1651417224590-937bf93c807e [250ms]
> [debug] [2022-05-01T15:00:24.657Z] Reading `package.json` file
> [debug] [2022-05-01T15:00:24.657Z] Reading `vercel.json` file
> [debug] [2022-05-01T15:00:24.657Z] No `vercel.json` file present
> [debug] [2022-05-01T15:00:24.662Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev
> [debug] [2022-05-01T15:00:24.664Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.git
> [debug] [2022-05-01T15:00:24.664Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.gitignore
> [debug] [2022-05-01T15:00:24.665Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.vercel
> [debug] [2022-05-01T15:00:24.665Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/node_modules
> [debug] [2022-05-01T15:00:24.667Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev [5ms]
> Running Dev Command “svelte-kit dev --port $PORT”
> [debug] [2022-05-01T15:00:24.682Z] Starting dev command with parameters : {"cwd":"/Users/ssadowski/projects/svelte-chicago/sveltechi.dev","command":"svelte-kit dev --port 53162","port":53162}
> [debug] [2022-05-01T15:00:24.683Z] Spawning dev command: npx --no-install svelte-kit dev --port 53162
> [debug] [2022-05-01T15:00:24.685Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev
> [debug] [2022-05-01T15:00:24.685Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.git
> [debug] [2022-05-01T15:00:24.685Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.gitignore
> [debug] [2022-05-01T15:00:24.685Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.vercel
> [debug] [2022-05-01T15:00:24.685Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/node_modules
> [debug] [2022-05-01T15:00:24.687Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev [2ms]

  SvelteKit v1.0.0-next.324


  Use --host to expose server to other devices on this network


> [debug] [2022-05-01T15:00:25.482Z] Filesystem watcher notified of 25 events
> [debug] [2022-05-01T15:00:25.484Z] File modified: .svelte-kit/runtime/app/env.js
> [debug] [2022-05-01T15:00:25.484Z] File modified: .svelte-kit/runtime/app/navigation.js
> [debug] [2022-05-01T15:00:25.484Z] File modified: .svelte-kit/runtime/app/paths.js
> [debug] [2022-05-01T15:00:25.485Z] File modified: .svelte-kit/runtime/app/stores.js
> [debug] [2022-05-01T15:00:25.485Z] File modified: .svelte-kit/runtime/client/singletons.js
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/client/start.js
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/components/error.svelte
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/components/layout.svelte
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/env.js
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/paths.js
> [debug] [2022-05-01T15:00:25.486Z] File modified: .svelte-kit/runtime/server/index.js
> [debug] [2022-05-01T15:00:25.487Z] File modified: .svelte-kit/tsconfig.json
> [debug] [2022-05-01T15:00:25.487Z] File modified: .svelte-kit/generated/client-manifest.js
> [debug] [2022-05-01T15:00:25.487Z] File modified: .svelte-kit/generated/root.svelte
> [debug] [2022-05-01T15:00:25.487Z] File modified: .svelte-kit/generated/client-matchers.js
> [debug] [2022-05-01T15:00:25.487Z] File modified: .svelte-kit/types/src/routes/__layout.d.ts
> [debug] [2022-05-01T15:00:25.488Z] File modified: .svelte-kit/types/src/routes/event/[id].d.ts
> [debug] [2022-05-01T15:00:25.488Z] File modified: .svelte-kit/types/src/routes/events.d.ts
> [debug] [2022-05-01T15:00:25.488Z] File modified: .svelte-kit/types/src/routes/index.d.ts
> [debug] [2022-05-01T15:00:25.488Z] File modified: .svelte-kit/runtime/components/error.svelte
> [debug] [2022-05-01T15:00:25.488Z] File modified: .svelte-kit/runtime/components/layout.svelte
> [debug] [2022-05-01T15:00:25.490Z] File modified: .svelte-kit/runtime/client/start.js
> [debug] [2022-05-01T15:00:25.490Z] File modified: .svelte-kit/runtime/env.js
> [debug] [2022-05-01T15:00:25.490Z] File modified: .svelte-kit/runtime/paths.js
> [debug] [2022-05-01T15:00:25.490Z] File modified: .svelte-kit/tsconfig.json
> [debug] [2022-05-01T15:00:25.490Z] Reading `package.json` file
> [debug] [2022-05-01T15:00:25.491Z] Reading `vercel.json` file
> [debug] [2022-05-01T15:00:25.491Z] No `vercel.json` file present
> [debug] [2022-05-01T15:00:25.492Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev
> [debug] [2022-05-01T15:00:25.492Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.git
> [debug] [2022-05-01T15:00:25.492Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.gitignore
> [debug] [2022-05-01T15:00:25.492Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/.vercel
> [debug] [2022-05-01T15:00:25.492Z] Ignoring /Users/ssadowski/projects/svelte-chicago/sveltechi.dev/node_modules
> [debug] [2022-05-01T15:00:25.495Z] Locating files /Users/ssadowski/projects/svelte-chicago/sveltechi.dev [3ms]
> [debug] [2022-05-01T15:00:54.694Z] No builders were updated
> [debug] [2022-05-01T15:05:24.765Z] Closing file watcher
Error! Detecting port 53162 timed out after 300000ms
> [debug] [2022-05-01T15:05:24.829Z] Error: Detecting port 53162 timed out after 300000ms
    at checkForPort (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236627:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DevServer.runDevCommand (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236434:9)
    at DevServer._start (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236045:9)
> [debug] [2022-05-01T15:05:24.835Z] handling rejection
Error! An unexpected error occurred!
Error: Detecting port 53162 timed out after 300000ms
    at checkForPort (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236627:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DevServer.runDevCommand (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236434:9)
    at DevServer._start (/opt/homebrew/Cellar/vercel-cli/24.2.0/libexec/lib/node_modules/vercel/dist/index.js:236045:9)
> [debug] [2022-05-01T15:05:24.837Z] #6 → GET https://api.vercel.com/v2/user
> [debug] [2022-05-01T15:05:25.118Z] #6 ← 200 OK: sfo1::zzl9p-1651417525103-cf2dd574aee0 [281ms]
```

**Comment by sjsadowski** [comment]
More to add: this only happens when there are two projects linked to the same repository that are in use by the same user, as far as I can tell.

**Comment by GuillermoCasanova** [comment]
Anyone have a fix for this?

**Comment by bitaccesscomau** [comment]
Also experiencing this problem with SvelteKit as of a couple days ago. It was previously running with default config at port 3000. Now it opens on 5173 and crashes entirely after 300000ms producing the below error.

```
Error: Detecting port 61371 timed out after 300000ms
> [debug] [2024-09-12T23:27:36.747Z] Error: Detecting port 61371 timed out after 300000ms
    at checkForPort (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:167711:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runDevCommand (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:169453:32)
    at async DevServer._getVercelConfig (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:168876:9)
> [debug] [2024-09-12T23:27:36.760Z] handling rejection
Error: An unexpected error occurred!
Error: Detecting port 61371 timed out after 300000ms
    at checkForPort (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:167711:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runDevCommand (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:169453:32)
    at async DevServer._getVercelConfig (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:168876:9)
> [debug] [2024-09-12T23:27:36.763Z] #4 → GET https://api.vercel.com/v2/user
> [debug] [2024-09-12T23:27:36.970Z] Dev command exited with "0"
> [debug] [2024-09-12T23:27:36.970Z] Dev command closed with "0"
> [debug] [2024-09-12T23:27:37.329Z] #4 ← 200 OK: sfo1::tk6ds-1726183657328-d024c3efbd94 [566ms]
```

**Comment by callmeaponte** [comment]
I'm also experiencing this same issue with the latest versions of the `vercel` and `sveltejs/kit` packages.

I tried the [older workaround](https://github.com/vercel/vercel/issues/8121#issuecomment-1226454969) of using `vite --port $PORT --host 0.0.0.0` but that doesn't seem to work.

**Comment by magnuslundin** [comment]
I just upgraded to the latest version of the CLI and started to experience this. Any news?

**Comment by trek** [comment]
Ach! My bad everyone. I know the solution for this and have a card for it in Linear but then failed to assign it to myself so it dropped off my radar.

The root cause isn't svelte itself, it's svelte moving to vite, and vite [not respecting `process.env.PORT`](https://github.com/vitejs/vite/issues/5280) which is... a choice. `process.env.PORT` isn't quite a standard but basically every other framework detects and uses this so it's how we tell the underlying framework's development server where to bind and how we pass incoming requests to it. 

The current workaround until we fix and release would be adding:

```
	server: {
		port: process.env.PORT
	},
```

To your project's `vite.config.js`
