### ISSUE TITLE
Error: Command "vercel build" exited with 1

### ISSUE THREAD

**Issue by kxnakr** [zeit/now#7914]
Getting this error on vercel but my local machine can build it without any errors

Error at:
```
TypeError: project.slug.split(...).at is not a function
```

My code:
```jsx
import { allProjects, Project } from "@contentlayer/generated";

export async function getStaticPaths() {
  const paths = allProjects.map((project) => ({
    // both gave the same error 
    // params: { slug: project.slug.split("/").at(-1)},
    params: { slug: typeof project.slug === "string" ? project.slug.split("/").at(-1) : "" },
  }));

  return {
    paths,
    fallback: false,
  };
}
```

Logs:
```
[01:55:28.261] Cloning github.com/krishna8421/krishnaaa.com (Branch: main, Commit: 746fe1b)
[01:55:29.521] Cloning completed: 1.260s
[01:55:29.951] Looking up build cache...
[01:55:30.085] Build Cache not found
[01:55:30.547] Running "vercel build"
[01:55:31.376] Vercel CLI 24.2.5-canary.2 build (beta) — https://vercel.com/feedback
[01:55:31.797] Installing dependencies...
[01:55:32.468] yarn install v1.22.17
[01:55:32.635] [1/4] Resolving packages...
[01:55:33.255] [2/4] Fetching packages...
[01:56:30.476] [3/4] Linking dependencies...
[01:56:30.486] warning "contentlayer > @contentlayer/utils > @opentelemetry/exporter-trace-otlp-grpc > @opentelemetry/core@1.0.1" has incorrect peer dependency "@opentelemetry/api@>=1.0.0 <1.1.0".
[01:56:30.487] warning "contentlayer > @contentlayer/utils > @opentelemetry/exporter-trace-otlp-grpc > @opentelemetry/resources@1.0.1" has incorrect peer dependency "@opentelemetry/api@>=1.0.0 <1.1.0".
[01:56:30.487] warning "contentlayer > @contentlayer/utils > @opentelemetry/exporter-trace-otlp-grpc > @opentelemetry/sdk-trace-base@1.0.1" has incorrect peer dependency "@opentelemetry/api@>=1.0.0 <1.1.0".
[01:56:30.500] warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
[01:56:30.500] warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
[01:56:30.501] warning "next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
[01:56:30.501] warning "next-pwa > terser-webpack-plugin@5.3.1" has unmet peer dependency "webpack@^5.1.0".
[01:56:30.501] warning "next-pwa > workbox-webpack-plugin@6.5.3" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
[01:56:30.608] warning Workspaces can only be enabled in private projects.
[01:56:30.610] warning Workspaces can only be enabled in private projects.
[01:56:30.630] warning Workspaces can only be enabled in private projects.
[01:56:51.957] [4/4] Building fresh packages...
[01:56:58.204] $ husky install
[01:56:58.346] husky - Git hooks installed
[01:56:58.352] Done in 85.89s.
[01:56:58.401] Detected Next.js version: 12.1.6
[01:56:58.403] Running "yarn run build"
[01:56:58.830] yarn run v1.22.17
[01:56:58.899] $ next build
[01:57:00.969] warn  - You have enabled experimental feature(s).
[01:57:00.970] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
[01:57:00.970] 
[01:57:00.971] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[01:57:05.352] Generated 1 documents in .contentlayer
[01:57:05.381] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[01:57:05.381] This information is used to shape Next.js' roadmap and prioritize features.
[01:57:05.382] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[01:57:05.382] https://nextjs.org/telemetry
[01:57:05.382] 
[01:57:05.446] info  - Checking validity of types...
[01:57:17.738] info  - Creating an optimized production build...
[01:57:17.766] warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
[01:57:17.835] > [PWA] Compile client (static)
[01:57:17.837] > [PWA] Auto register service worker with: /vercel/path0/node_modules/next-pwa/register.js
[01:57:17.838] > [PWA] Service worker: /vercel/path0/public/sw.js
[01:57:17.841] > [PWA]   url: /sw.js
[01:57:17.842] > [PWA]   scope: /
[01:57:18.208] > [PWA] Compile server
[01:57:18.212] > [PWA] Compile server
[01:57:40.246] info  - Compiled successfully
[01:57:40.246] info  - Collecting page data...
[01:57:40.955] 
[01:57:40.956] > Build error occurred
[01:57:40.962] TypeError: project.slug.split(...).at is not a function
[01:57:40.963]     at /vercel/path0/.next/server/pages/projects/[slug].js:117:82
[01:57:40.963]     at Array.map (<anonymous>)
[01:57:40.964]     at getStaticPaths (/vercel/path0/.next/server/pages/projects/[slug].js:115:98)
[01:57:40.965]     at buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:37)
[01:57:40.966]     at /vercel/path0/node_modules/next/dist/build/utils.js:632:125
[01:57:40.971]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[01:57:40.971]   type: 'TypeError'
[01:57:40.971] }
[01:57:41.041] error Command failed with exit code 1.
[01:57:41.041] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[01:57:41.071] Error! Command "yarn run build" exited with 1
[01:57:41.146] Error: Command "vercel build" exited with 1
```

**Comment by kxnakr** [comment]
I fixed the error by removing ```.at(-1)``` to the old index way and it worked.
