### ISSUE TITLE
I install the last version of vercel cli and i have a error

### ISSUE THREAD

**Issue by gusantoscode** [zeit/now#7947]
```
/usr/local/lib/node_modules/vercel/dist/index.js:202574
        .filter((b) => Boolean(b.config && b.config.zeroConfig && b.src?.startsWith('api/')))
                                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
gustavo@gustavo-pc:~/Documents/projetos/portfolio-prov$ vc dev
/usr/local/lib/node_modules/vercel/dist/index.js:202574
        .filter((b) => Boolean(b.config && b.config.zeroConfig && b.src?.startsWith('api/')))
                                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by simonw** [comment]
I just encountered this bug too, trying to deploy to Vercel from GitHub Actions. Here's my workflow: https://github.com/simonw/til/blob/e3ad444af8b405fc93ba62fbb4f52dcde6b3c232/.github/workflows/build.yml

I'm using the Vercel CLI that comes bundled with GitHub Actions - according to https://github.com/actions/virtual-environments/blob/c9a93eb735fa5264acca9afd5c0c6b9348c8e407/images/linux/Ubuntu2004-Readme.md#cli-tools it's Vercel CLI 25.0.0, as of 5 days ago.

**Comment by simonw** [comment]
It turns out the problem for me was that I was installing Node.js 12 in my workflow, and Vercel 25.0.0 dropped support for that version: https://github.com/vercel/vercel/releases/tag/vercel%4025.0.0
