### ISSUE TITLE
Build Failed - The Environment Variables provided for your Serverless Functions exceed the limit of 4KB

### ISSUE THREAD

**Issue by PGuimarais** [zeit/now#8105]
I recently pushed a text change on a webpage, and now my builds are failing with the following message. 

```
Build Failed
The Environment Variables provided for your Serverless Functions exceed the limit of 4KB. Reduce their size to continue.
```

According to [this page](https://vercel.com/docs/concepts/limits/overview#environment-variables) each environment can have a total of 100 variables; ours have 56. We did not update or change our environment variables prior to this build failure.

The following error appears in the build log:

`

Traced Next.js server files in: 373.228ms
--
18:07:16.940 | Created all serverless functions in: 7.939s
18:07:16.981 | Collected static files (public/, static/, .next/static): 36.185ms
18:07:25.909 | AssertionError [ERR_ASSERTION]: undefined == true
18:07:25.910 | at /var/task/sandbox.js:279:3350
18:07:25.910 | at runMicrotasks (<anonymous>)
18:07:25.910 | at processTicksAndRejections (internal/process/task_queues.js:95:5) {
18:07:25.910 | generatedMessage: true,
18:07:25.910 | code: 'ERR_ASSERTION',
18:07:25.910 | actual: undefined,
18:07:25.910 | expected: true,
18:07:25.910 | operator: '==',
18:07:25.910 | step: 'UPLOADING_BUILD_OUTPUTS'
18:07:25.911 | }

`

We re-ran a previously successful build, and it failed with the same message. Has anyone else run into this issue?

**Comment by PGuimarais** [comment]
Update: I removed an integration with Logtail and it appears to have resolved this issue (there are 2 env variables associated with the integration)

I do not think it has to do with the environment variables, as there was no change to them and Logtail was working for some time; I suspect the issue is related to the integration.
