### ISSUE TITLE
`vercel dev` in Vite app causes port timeout

### ISSUE THREAD

**Issue by kbrgl** [zeit/now#8121]
I get the following error after a while running vercel dev in a Vite/SvelteKit app:

```
Error! Detecting port 62323 timed out after 300000ms
Error! An unexpected error occurred!
Error: Detecting port 62323 timed out after 300000ms
    at checkForPort (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243842:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DevServer.runDevCommand (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243643:9)
    at DevServer._start (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243267:9)
Error! An unexpected error occurred!
Error: Detecting port 62323 timed out after 300000ms
    at checkForPort (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243842:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DevServer.runDevCommand (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243643:9)
    at DevServer._start (/Users/kabir/Library/pnpm/global/5/.pnpm/vercel@27.0.0/node_modules/vercel/dist/index.js:243267:9)
```

**Comment by verbose117** [comment]
I guess maybe this is because that port was already in use!

can you share the source code you are working with?

**Comment by bartoszwalicki** [comment]
I have the same problem on Mac M1 12.4. No matter which port I will use I cannot access application (Angular) nor Functions.

Vercel CLI 27.1.5
Node: v18.3.0

```bash
Error! Detecting port 56809 timed out after 300000ms
Error! An unexpected error occurred!
Error: Detecting port 56809 timed out after 300000ms
    at checkForPort (/opt/homebrew/lib/node_modules/vercel/dist/index.js:244204:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DevServer.runDevCommand (/opt/homebrew/lib/node_modules/vercel/dist/index.js:244005:9)
    at DevServer._start (/opt/homebrew/lib/node_modules/vercel/dist/index.js:243629:9)
```

**Comment by beltranrengifo** [comment]
I've migrated from create-react-app setting to use Vite and everything works locally using the standard dev command. However as it is expected, serverless functions are not available.

Overriding the project dev command to `vite --port $PORT` and running `vercel dev` locally provokes the timeout, as mentioned above.

Deployed on Vercel, everything works.
[Demo site](https://lug-spain-site-4v1590mtp-lugspain.vercel.app/)
[Code](https://github.com/lugspain/portal/tree/vite-setup)

Any idea how to make work the serverless functions locally with Vite?
Thank you!

**Comment by kbrgl** [comment]
@haneenmahd port definitely wasn't bound, I checked that. Could this be some sort of memory leak?

**Comment by verbose117** [comment]
Yes, I previously had experienced memory leak when using `vercel` with the [MUI](https://github.com/mui/material-ui) project on my M1 MBP. It was caused when I was working on the project continuously for almost just 30 minutes. It also have thrown other internal node.js errors. Maybe because vercel's consuming a lot of memory.

- Did this happen right after running `vercel dev`?
  - If yes, please share the complete log or a project to reproduce this issue?

**Comment by styfle** [comment]
The workaround is to use `vite --port $PORT --host 0.0.0.0` as your development command.

I think we'll need to update `vercel dev` to support both ipv4 and ipv6 as more frameworks change to ipv6.

**Comment by qodesmith** [comment]
> The workaround is to use vite --port $PORT --host 0.0.0.0 as your development command.

It took me a long time to realize this was referring to the dev command _in your vercel account project settings_! I was banging my head against the wall trying with the local `package.json` 🙃 

<img width="938" alt="Screen Shot 2022-08-27 at 9 04 19 AM" src="https://user-images.githubusercontent.com/11034792/187031520-421fdc16-e221-41c2-a7f1-c70d00602713.png">

**Comment by styfle** [comment]
This should be fixed by #8542

**Comment by styfle** [comment]
The fix is available on the latest version of Vercel CLI

    npm i -g vercel@latest

**Comment by unitof** [comment]
Working beautifully, thanks for besing & dosing @styfle & @TooTallNate!

**Comment by unicornware** [comment]
@styfle do you know if #8542 is intended to fix this issue only if vite is used directly or if there are additional options i should pass to the vercel cli if not using vite directly?

i'm still running into this error when running [`vitepress dev docs`][1] via `vc dev`:

```sh
Error: Detecting port 63484 timed out after 300000ms
Error: An unexpected error occurred!
Error: Detecting port 63484 timed out after 300000ms
    at checkForPort (/Users/lex/Projects/FLDV/FLDV-P021/node_modules/vercel/dist/index.js:242046:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DevServer.runDevCommand (/Users/lex/Projects/FLDV/FLDV-P021/node_modules/vercel/dist/index.js:241842:32)
    at DevServer._getVercelConfig (/Users/lex/Projects/FLDV/FLDV-P021/node_modules/vercel/dist/index.js:241252:9)
```

as per your suggestion, i tried setting `server.host` (and `server.hmr.host`) to `0.0.0.0`, but the same error occurs. it did take a longer time for the error to appear, but in general, it occurs so frequently that i'm considering scrapping the `vc dev` command altogether to use a combination of `vc env pull` and `vitepress dev docs`.

---

- node: `16.17.0`
- vercel: `28.4.12`
- vite: `3.1.8`

[1]: https://vitepress.vuejs.org/guide/getting-started#step-3-boot-up-dev-environment

**Comment by thomas-kuhlmann** [comment]
@styfle I seem to be running into the same problem - just set up a new vue 3 project, and trying to run `vercel dev` errors out with (every time with a different port though):

> Error: Detecting port 41461 timed out after 300000ms
> Error: An unexpected error occurred!
> Error: Detecting port 41461 timed out after 300000ms
>     at checkForPort (/home/thomaskuhlmann/.volta/tools/image/packages/vercel/lib/node_modules/vercel/dist/index.js:236761:15)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at DevServer.runDevCommand (/home/thomaskuhlmann/.volta/tools/image/packages/vercel/lib/node_modules/vercel/dist/index.js:236554:32)
>     at DevServer._getVercelConfig (/home/thomaskuhlmann/.volta/tools/image/packages/vercel/lib/node_modules/vercel/dist/index.js:235971:9)

-------

I have tried:

- setting the development command for my project to `vite --port $PORT --host 0.0.0.0` and I can open the page and work until the timeout occurs.
- adding `"devCommand": "npm run dev"` to `vercel.json`

none of it made a difference.

------

- node: `18.17.1`
- vercel: `32.2.4`
- vite: `4.4.9`

**Comment by qkdreyer** [comment]
~same issue using node v20.10.0 vercel v34.2.4 vite v3.2.10~
edit: actually I fixed it by updating my vercel project settings from Vue.js to Vite (@ThomasKuhlmann if it can help you)

**Comment by NaughtyDog6000** [comment]
using sveltekit and vercel cli and encountered this issue on a new os install with all the latest tools

**Comment by martinpaljak** [comment]
Same here, the port is unrelated to the port where vite actually runs the dev server.

**Comment by bitaccesscomau** [comment]
Also experiencing this problem with SvelteKit as of a couple days ago. It was previously running with default config at port 3000. Now it opens on 5173 and crashes entirely after 300000ms producing the below error.
```
Error: Detecting port 61371 timed out after 300000ms
> [debug] [2024-09-12T23:27:36.747Z] Error: Detecting port 61371 timed out after 300000ms
    at checkForPort (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:167711:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runDevCommand (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:169453:32)
    at async DevServer._getVercelConfig (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:168876:9)
> [debug] [2024-09-12T23:27:36.760Z] handling rejection
Error: An unexpected error occurred!
Error: Detecting port 61371 timed out after 300000ms
    at checkForPort (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:167711:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runDevCommand (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:169453:32)
    at async DevServer._getVercelConfig (/Users/x/Library/pnpm/global/5/.pnpm/vercel@37.0.0/node_modules/vercel/dist/index.js:168876:9)
> [debug] [2024-09-12T23:27:36.763Z] #4 → GET https://api.vercel.com/v2/user
> [debug] [2024-09-12T23:27:36.970Z] Dev command exited with "0"
> [debug] [2024-09-12T23:27:36.970Z] Dev command closed with "0"
> [debug] [2024-09-12T23:27:37.329Z] #4 ← 200 OK: sfo1::tk6ds-1726183657328-d024c3efbd94 [566ms]
```

**Comment by ndru123** [comment]
same problem here with sveltekit

**Comment by callmeaponte** [comment]
+ 1 I'm experiencing this same issue with the latest versions of `vercel` package, and `sveltejs/kit` packages.

Also, we're commenting on a closed PR... I wonder if anyone on the Vercel team is even checking this?

**Comment by austeane** [comment]
Same problem

**Comment by jedikcz** [comment]
Same problem here with latest Vercel CLI (37.14.0)

**Comment by trek** [comment]
@austeane @jedikcz @ndru123 there is a new root cause for what you're seeing https://github.com/vercel/vercel/issues/12581
