### ISSUE TITLE
nx-ignore runs into "Cannot find module typescript" on deploy only

### ISSUE THREAD

**Issue by mcmxcdev** [zeit/now#8196]
We encounter this stacktrace for a couple of days now and the only way to fix it is by rerunning without cache:

```
[07:51:55.942] Cloning github.com/org/repo (Branch: chore/update-eslint-ruleset, Commit: 49a5473)
[07:51:56.452] Cloning completed: 509.394ms
[07:51:56.452] Running "npm i -g typescript && npx nx-ignore foo"
[07:51:58.129] /node14/bin/tsc -> /node14/lib/node_modules/typescript/bin/tsc
[07:51:58.129] /node14/bin/tsserver -> /node14/lib/node_modules/typescript/bin/tsserver
[07:51:58.132] + typescript@4.7.4
[07:51:58.132] added 1 package from 1 contributor in 1.286s
[07:52:04.780] ≫ Using Nx to determine if this project (foo) is affected by the commit...
[07:52:05.959] ✅ - Build can proceed since foo is affected
[07:52:07.045] Looking up build cache...
[07:52:17.201] Build cache downloaded [176.11 MB]: 9414.916ms
[07:52:17.444] Running "vercel build"
[07:52:17.899] Vercel CLI 27.1.5
[07:52:18.426] Detected `pnpm-lock.yaml` generated by pnpm 7...
[07:52:18.466] Installing dependencies...
[07:52:19.013] Scope: all 4 workspace projects
[07:52:19.281] Lockfile is up-to-date, resolution step is skipped
[07:52:19.589] Already up-to-date
[07:52:20.844] 
[07:52:20.846] . prepare$ husky install
[07:52:20.934] . prepare: husky - Git hooks installed
[07:52:20.937] . prepare: Done
[07:52:20.957] Detected Next.js version: 12.2.2
[07:52:21.154] Running "npx nx build foo"
[07:52:21.825] nx.js run [project][:target][:configuration] [_..]
[07:52:21.825] 
[07:52:21.825] Run a target for a project
[07:52:21.825]     (e.g., nx run myapp:serve:production).
[07:52:21.825] 
[07:52:21.825]     You can also use the infix notation to run a target:
[07:52:21.826]     (e.g., nx serve myapp --configuration=production)
[07:52:21.826] 
[07:52:21.826]     You can skip the use of Nx cache by using the --skip-nx-cache option.
[07:52:21.826] 
[07:52:21.826] Options:
[07:52:21.826]       --version           Show version number  [boolean]
[07:52:21.826]       --prod              Use the production configuration  [boolean] [default: false]
[07:52:21.826]   -c, --configuration     Target configuration  [string]
[07:52:21.826]       --project           Target project  [string]
[07:52:21.826]       --output-style      Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
[07:52:21.827]       --nx-bail           Stop command execution after the first failed task  [boolean] [default: false]
[07:52:21.827]       --nx-ignore-cycles  Ignore cycles in the task graph  [boolean] [default: false]
[07:52:21.827] 
[07:52:21.828] {
[07:52:21.828]   stack: "Error: Cannot find module 'typescript'\n" +
[07:52:21.828]     'Require stack:\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/index.js\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js\n' +
[07:52:21.828]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/server.js\n' +
[07:52:21.829]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/start.js\n' +
[07:52:21.829]     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n' +
[07:52:21.829]     '    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n' +
[07:52:21.829]     '    at Module.require (internal/modules/cjs/loader.js:974:19)\n' +
[07:52:21.829]     '    at require (internal/modules/cjs/helpers.js:101:18)\n' +
[07:52:21.830]     '    at new TypeScriptImportLocator (/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js:11:20)\n' +
[07:52:21.830]     '    at buildExplicitTypeScriptDependencies (/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js:7:27)\n' +
[07:52:21.830]     '    at buildExplicitTypescriptAndPackageJsonDependencies (/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/build-explicit-typescript-and-package-json-dependencies.js:10:98)\n' +
[07:52:21.830]     '    at buildExplicitDependenciesWithoutWorkers (/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js:161:117)\n' +
[07:52:21.830]     '    at buildExplicitDependencies (/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js:118:16)\n' +
[07:52:21.831]     '    at /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js:83:15',
[07:52:21.831]   message: "Cannot find module 'typescript'\n" +
[07:52:21.831]     'Require stack:\n' +
[07:52:21.831]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js\n' +
[07:52:21.831]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js\n' +
[07:52:21.831]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/index.js\n' +
[07:52:21.832]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js\n' +
[07:52:21.832]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js\n' +
[07:52:21.832]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/server.js\n' +
[07:52:21.832]     '- /vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/start.js\n' +
[07:52:21.832]     '\n' +
[07:52:21.833]     'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
[07:52:21.833]     'If the error persists, please run "nx reset".',
[07:52:21.833]   code: 'MODULE_NOT_FOUND',
[07:52:21.833]   requireStack: [
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-dependencies/index.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/project-graph/build-project-graph.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/server.js',
[07:52:21.834]     '/vercel/.npm/_npx/274/lib/node_modules/nx-ignore/node_modules/nx/src/daemon/server/start.js'
[07:52:21.834]   ]
[07:52:21.834] }
[07:52:21.901] Error: Command "npx nx build foo" exited with 1
```

**Comment by octalpixel** [comment]
+1 on this. Getting the same error

**Comment by ArnasJack** [comment]
Did you find a solution for this?

I have the same issue after integrating Setry, but my error is:
`Inner Error: Error: Cannot find module '@sentry/nextjs'`

Also works fine when rerunning without cache.
