### ISSUE TITLE
500 errors for Vercel Python: "There is no current event loop in thread"

### ISSUE THREAD

**Issue by simonw** [zeit/now#8231]
I'm getting the following error from ALL of my Python functions - for example on https://til.simonwillison.net/ which logs to https://vercel.com/datasette/simon-til/9SYmpgw4ExnTbRLnsevw5zXXTRgb/functions

```
[ERROR] RuntimeError: There is no current event loop in thread 'MainThread'.
Traceback (most recent call last) :
  File "/var/task/vc handler python.py", line 453, in vc_handler
    lifespan = Lifespan( vc module.app)
  File "/var/task/vc handler python.py", line 308, in init
    self. loop = get event loop()
  File "/var/task/vc handler_python. py", line 184, in get_event_loop
    return asyncio.get event_loop()
  File "/var/lang/lib/python3.g/asyncio/events.py" line 642, in get _event_loop
    raise RuntimeError('There is no current event loop in thread er.
```

Full details here:
- https://github.com/simonw/datasette-publish-vercel/issues/58

I first encountered this error this afternoon. I think it's caused by this commit here, which applied fixes involving `asyncio.get event_loop()` for Python 3.10: https://github.com/vercel/vercel/commit/66c8544e8fb7b8eb77106d8b428ef6736b9ecb45

I would upgrade to Python 3.10 but as far as I can tell that's not possible yet - the docs at https://vercel.com/docs/runtimes#official-runtimes/python/python-version suggest that only Python 3.9 is supported at the moment.

**Comment by simonw** [comment]
I found a workaround: pinning to the previous release of `@vercel/python`:

        "use": "@vercel/python@3.0.7"

Added to my `vercel.json`:

```json
{
    "name": "simon-til",
    "version": 2,
    "builds": [
        {
            "src": "index.py",
            "use": "@vercel/python@3.0.7"
        }
    ],
    "routes": [
        {
            "src": "(.*)",
            "dest": "index.py"
        }
    ]
}
```

After applying that fix https://til.simonwillison.net/ loads correctly again.
