### ISSUE TITLE
Python ASGI runtime creates an event loop on each request

### ISSUE THREAD

**Issue by vrslev** [zeit/now#8477]
Current ASGI runtime is quite inefficient: it creates new event loop and queue on each function call.

https://github.com/vercel/vercel/blob/b05d653cf1ce93735cfce36ef364dd9937c52627/packages/python/vc_init.py#L191

We can avoid dealing with event loops and queues with `asyncio.run()`.

**Comment by rboixaderg** [comment]
We have some problems with new event loop en each request. We use the current event loop for other tasks when we init our app, and if you create a new event loop we have some conflicts with this.

It would be interesting to change the `new_event_loop` to `get_running_loop` and if there is no loop running, create it.

Thanks!

**Comment by WhaleFell** [comment]
Yes, I always meet about `attached to a different loop` error in my fastapi when I use httpx to request some website.

I have a stupid solution to fix this error. To add a retry decorator to any async function when u use the async module. 

my error log in vercel:

```log
2023-12-19 08:50:21.426 | ERROR    | app.helper.func:wrapper:43 - retry 1 times.reason: Task <Task pending name='starlette.middleware.base.BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro' coro=<BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro() running at /var/task/starlette/middleware/base.py:70> cb=[TaskGroup._spawn.<locals>.task_done() at /var/task/anyio/_backends/_asyncio.py:661]> got Future <Future pending> attached to a different loop
```
![image](https://github.com/vercel/vercel/assets/63758849/cdef74e1-d0eb-47b4-9718-5a1d6662f94e)
![image](https://github.com/vercel/vercel/assets/63758849/979d0bfe-ad3b-4271-9601-4d087c168743)

**Comment by WhaleFell** [comment]
Today, I caught the error when I sand http requests by `httpx` module in vercel fastapi. This is a full error trackback. I regard this as the vercel python runtime bug because not bug happened when I ran it on by laptop myself.

In addition,the error only occurred when I used asynchronous modules or functions. Another mention in https://github.com/vercel/vercel/issues/8477

```log
Traceback (most recent call last):
  File "/var/task/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
  File "/var/lang/lib/python3.9/ssl.py", line 889, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/app/helper/func.py", line 42, in wrapper
    return await func(*args, **kwargs)
  File "/var/task/app/helper/onedrive_sdk.py", line 251, in get_file_download_url
    response = await self.client.get(api_url, headers=headers)
  File "/var/task/httpx/_client.py", line 1786, in get
    return await self.request(
  File "/var/task/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/var/task/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/var/task/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/var/task/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/var/task/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/var/task/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/var/task/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/var/task/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/var/task/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/var/task/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/var/task/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/var/task/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/var/task/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
  File "/var/task/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/var/task/anyio/streams/tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/var/task/anyio/streams/tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/var/task/anyio/_backends/_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
  File "/var/lang/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
RuntimeError: Task <Task pending name='starlette.middleware.base.BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro' coro=<BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro() running at /var/task/starlette/middleware/base.py:70> cb=[TaskGroup._spawn.<locals>.task_done() at /var/task/anyio/_backends/_asyncio.py:661]> got Future <Future pending> attached to a different loop
```
