### ISSUE TITLE
vercel dev crashes locally, but next dev does not

### ISSUE THREAD

**Issue by jakeleventhal** [zeit/now#9879]
### Discussed in https://github.com/vercel/vercel/discussions/9878

<div type='discussions-op-text'>

<sup>Originally posted by **jakeleventhal** April 30, 2023</sup>
### Problem Description

I am able to run `next dev` locally. When I run `vercel dev` I get this error
```
Server Error
TypeError: Cannot read properties of null (reading 'useContext')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
I get the same error for `useMemo` as well. Not sure what could be causing this issue.</div>

**Comment by jakeleventhal** [comment]
So, I was actually able to solve this. Turns out by changing the default "dev" command in my project settings to `npm run start` does the trick. 
```json
"start": "next dev"
```
I don't see why this would make any difference

**Comment by jd-carroll** [comment]
It looks like this is a larger problem. I suspect that you would get this error any time you try and run the build on vercel's site. (Which is the case for me)

```
TypeError: Cannot read properties of null (reading 'useEffect')
--
16:16:37.962 | at exports.useEffect (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:292)
16:16:37.962 | at Analytics (file:///vercel/path0/node_modules/@vercel/analytics/src/react.tsx:33:3)
16:16:37.962 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
16:16:37.963 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
16:16:37.963 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.963 | at Je (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:122:100)
16:16:37.963 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:222)
16:16:37.964 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.964 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:215)
16:16:37.964 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
16:16:37.964 |  
16:16:37.964 | Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
16:16:37.965 | TypeError: Cannot read properties of null (reading 'useEffect')
16:16:37.965 | at exports.useEffect (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:292)
16:16:37.965 | at Analytics (file:///vercel/path0/node_modules/@vercel/analytics/src/react.tsx:33:3)
16:16:37.965 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
16:16:37.965 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
16:16:37.965 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.966 | at Je (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:122:100)
16:16:37.967 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:222)
16:16:37.967 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.967 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:215)
16:16:37.967 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
16:16:37.967 | TypeError: Cannot read properties of null (reading 'useEffect')
16:16:37.969 | at exports.useEffect (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:292)
16:16:37.970 | at Analytics (file:///vercel/path0/node_modules/@vercel/analytics/src/react.tsx:33:3)
16:16:37.972 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
16:16:37.972 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
16:16:37.972 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.972 | at Je (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:122:100)
16:16:37.972 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:222)
16:16:37.973 | at He (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:123:155)
16:16:37.973 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:215)
16:16:37.973 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
```

Going to open a separate issue

**Comment by himself65** [comment]
Same error here

**Comment by himself65** [comment]
```
TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.311 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.311 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.311 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.311 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.312 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.312 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.312 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.312 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.312 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.312 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.312 |  
22:46:04.313 | Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
22:46:04.313 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.313 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.313 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.313 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.313 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.313 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.313 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.313 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.314 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.314 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.314 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.314 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.315 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.315 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.315 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.315 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.315 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.315 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.315 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.316 |  
22:46:04.316 | Error occurred prerendering page "/_debug/login.dev". Read more: https://nextjs.org/docs/messages/prerender-error
22:46:04.316 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.316 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.316 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.316 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.317 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.317 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.317 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.317 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.317 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.317 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.317 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.317 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.318 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.318 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.318 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.318 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.318 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.318 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.318 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.318 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.318 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.318 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.319 |  
22:46:04.319 | Error occurred prerendering page "/_debug/broadcast.dev". Read more: https://nextjs.org/docs/messages/prerender-error
22:46:04.319 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.319 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.319 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.319 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.319 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.319 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.319 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.319 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.320 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.320 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.320 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.320 | info  - Generating static pages (3/14)
22:46:04.321 | TypeError: Cannot read properties of null (reading 'useMemo')
22:46:04.321 | at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
22:46:04.321 | at I18nextProvider (file:///vercel/path0/node_modules/react-i18next/dist/es/I18nextProvider.js:7:15)
22:46:04.321 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
22:46:04.321 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.321 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
22:46:04.322 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.322 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.322 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.322 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
22:46:04.322 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
22:46:04.322

<br class="Apple-interchange-newline">
```

**Comment by PaulNext** [comment]
![image](https://user-images.githubusercontent.com/100060836/236379243-440ecf79-a682-47d5-8288-f53a9d7afa44.png)
Just had the same error 😂

**Comment by 0OZ** [comment]
```rm -rf ./node_modules .next && yarn```
has solved the problem for me

**Comment by garinger** [comment]
> `rm -rf ./node_modules .next && yarn` has solved the problem for me

Did you ever end up fixing it? Getting the same error.

**Comment by 0ximjosh** [comment]
In terms of the useMemo error, this may be related, see if redeploying with a fresh cache fixes it
https://github.com/vercel/next.js/discussions/43942

**Comment by Athrun-Judah** [comment]
the same error in 14.0.2
